name: docker-build-matrix
trigger:
- 'basic-setup'
- 'windows-too'

variables:
    dockerRegistryEndpoint: localhost:5000
    imageName: az-matrix

jobs:
- template: build.yaml
  parameters:
    name: Linux





# - job : docker_build

#   displayName: docker build and tag for py versions
#   workspace:
#     clean: outputs
#   strategy:
#     matrix:
#       # Python35:
#       #   PYTHON_VERSION: 'python3.5'
#       #   containerImage: ubuntu:16.04
#       #   os: Linux
#       # Python36:
#       #   PYTHON_VERSION: 'python3.6'
#       #   containerImage: ubuntu:16.04
#       #   os: Linux
#       Python37:
#         PYTHON_VERSION: 'python3.7'
#         containerImage: ubuntu:16.04
#         os: Linux
#         isLatest: 'true'

#   steps:
#     - template: azure-pipelines.steps.yaml
#       parameters:
#         os: Linux
