name: docker-build-matrix
trigger:
- 'basic-setup'
- 'windows-too'

variables:
    dockerRegistryEndpoint: localhost:5000
    imageName: az-matrix

jobs:
- job: prerun
  displayName: Job preparation and expansion
  steps:
    - script: |
        PKG_VERSION=$(python3 -c 'import foobar; print(foobar.__version__)'); \
        PKG_NAME=${PYTHON_VERSION}-${PKG_VERSION}; \
        echo "##vso[task.setvariable variable=packageVersion;isOutput=true]${PKG_VERSION}"
        echo "##vso[task.setvariable variable=packageBasename;isOutput=true]${PKG_NAME}"
      name: setSharedVariables
      workingDirectory: ./src
      failOnStderr: true
      displayName: Generate package and basenames

- template: ./azure-pipelines.job.yaml
  parameters:
    name: Linux
    vmImage: ubuntu-16.04
    pyContainerSuffix: '-alpine'
    # 3.72-alpine38

- template: ./azure-pipelines.job.yaml
  parameters:
    name: Windows
    vmImage: win1803
    pyContainerSuffix: '-windowsservercore-1803'
    # 3.6-windowsservercore-1803

